CRITICAL - 2023-12-04 04:28:18 --> Access denied for user 'admin'@'localhost' (using password: YES)
in APPPATH\Views\connection.php on line 6.
 1 APPPATH\Views\connection.php(6): mysqli->__construct('localhost', 'admin', Object(SensitiveParameterValue), 'ci-4', 3306)
 2 APPPATH\Views\login_boot.php(2): include('C:\\xampp\\htdocs\\ci4\\app\\Views\\connection.php')
 3 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\ci4\\app\\Views\\login_boot.php')
 4 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1190): CodeIgniter\View\View->render('login_boot', [], true)
 6 APPPATH\Controllers\Home.php(15): view('login_boot')
 7 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->signin()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-04 04:29:57 --> Access denied for user 'admin'@'localhost' (using password: YES)
in APPPATH\Views\connection.php on line 6.
 1 APPPATH\Views\connection.php(6): mysqli->__construct('localhost', 'admin', Object(SensitiveParameterValue), 'ci-4', 3306)
 2 APPPATH\Views\login_boot.php(2): include('C:\\xampp\\htdocs\\ci4\\app\\Views\\connection.php')
 3 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\ci4\\app\\Views\\login_boot.php')
 4 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1190): CodeIgniter\View\View->render('login_boot', [], true)
 6 APPPATH\Controllers\Home.php(15): view('login_boot')
 7 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->signin()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-04 04:29:58 --> Access denied for user 'admin'@'localhost' (using password: YES)
in APPPATH\Views\connection.php on line 6.
 1 APPPATH\Views\connection.php(6): mysqli->__construct('localhost', 'admin', Object(SensitiveParameterValue), 'ci-4', 3306)
 2 APPPATH\Views\login_boot.php(2): include('C:\\xampp\\htdocs\\ci4\\app\\Views\\connection.php')
 3 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\ci4\\app\\Views\\login_boot.php')
 4 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1190): CodeIgniter\View\View->render('login_boot', [], true)
 6 APPPATH\Controllers\Home.php(15): view('login_boot')
 7 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->signin()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-04 04:30:23 --> Access denied for user 'admin'@'localhost' (using password: YES)
in APPPATH\Views\connection.php on line 6.
 1 APPPATH\Views\connection.php(6): mysqli->__construct('localhost', 'admin', Object(SensitiveParameterValue), 'ci-4', 3306)
 2 APPPATH\Views\login_boot.php(2): include('C:\\xampp\\htdocs\\ci4\\app\\Views\\connection.php')
 3 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\ci4\\app\\Views\\login_boot.php')
 4 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1190): CodeIgniter\View\View->render('login_boot', [], true)
 6 APPPATH\Controllers\Home.php(15): view('login_boot')
 7 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->signin()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-04 04:30:25 --> Access denied for user 'admin'@'localhost' (using password: YES)
in APPPATH\Views\connection.php on line 6.
 1 APPPATH\Views\connection.php(6): mysqli->__construct('localhost', 'admin', Object(SensitiveParameterValue), 'ci-4', 3306)
 2 APPPATH\Views\login_boot.php(2): include('C:\\xampp\\htdocs\\ci4\\app\\Views\\connection.php')
 3 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\ci4\\app\\Views\\login_boot.php')
 4 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1190): CodeIgniter\View\View->render('login_boot', [], true)
 6 APPPATH\Controllers\Home.php(15): view('login_boot')
 7 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->signin()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-04 05:05:22 --> Access denied for user 'admin'@'localhost' (using password: YES)
in APPPATH\Views\connection.php on line 6.
 1 APPPATH\Views\connection.php(6): mysqli->__construct('localhost', 'admin', Object(SensitiveParameterValue), 'ci-4')
 2 APPPATH\Views\login_boot.php(2): include('C:\\xampp\\htdocs\\ci4\\app\\Views\\connection.php')
 3 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\ci4\\app\\Views\\login_boot.php')
 4 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1190): CodeIgniter\View\View->render('login_boot', [], true)
 6 APPPATH\Controllers\Home.php(15): view('login_boot')
 7 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->signin()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-04 05:05:23 --> Access denied for user 'admin'@'localhost' (using password: YES)
in APPPATH\Views\connection.php on line 6.
 1 APPPATH\Views\connection.php(6): mysqli->__construct('localhost', 'admin', Object(SensitiveParameterValue), 'ci-4')
 2 APPPATH\Views\login_boot.php(2): include('C:\\xampp\\htdocs\\ci4\\app\\Views\\connection.php')
 3 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\ci4\\app\\Views\\login_boot.php')
 4 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1190): CodeIgniter\View\View->render('login_boot', [], true)
 6 APPPATH\Controllers\Home.php(15): view('login_boot')
 7 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->signin()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-04 05:06:28 --> Access denied for user 'root'@'localhost' (using password: YES)
in APPPATH\Views\connection.php on line 6.
 1 APPPATH\Views\connection.php(6): mysqli->__construct('localhost', 'root', Object(SensitiveParameterValue), 'ci-4')
 2 APPPATH\Views\login_boot.php(2): include('C:\\xampp\\htdocs\\ci4\\app\\Views\\connection.php')
 3 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\ci4\\app\\Views\\login_boot.php')
 4 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1190): CodeIgniter\View\View->render('login_boot', [], true)
 6 APPPATH\Controllers\Home.php(15): view('login_boot')
 7 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->signin()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-04 05:07:55 --> Undefined variable $username
in APPPATH\Views\connection.php on line 6.
 1 APPPATH\Views\connection.php(6): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $username', 'C:\\xampp\\htdocs\\ci4\\app\\Views\\connection.php', 6)
 2 APPPATH\Views\login_boot.php(2): include('C:\\xampp\\htdocs\\ci4\\app\\Views\\connection.php')
 3 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\ci4\\app\\Views\\login_boot.php')
 4 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1190): CodeIgniter\View\View->render('login_boot', [], true)
 6 APPPATH\Controllers\Home.php(15): view('login_boot')
 7 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->signin()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-04 05:08:09 --> Undefined variable $username
in APPPATH\Views\connection.php on line 6.
 1 APPPATH\Views\connection.php(6): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $username', 'C:\\xampp\\htdocs\\ci4\\app\\Views\\connection.php', 6)
 2 APPPATH\Views\login_boot.php(2): include('C:\\xampp\\htdocs\\ci4\\app\\Views\\connection.php')
 3 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\ci4\\app\\Views\\login_boot.php')
 4 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1190): CodeIgniter\View\View->render('login_boot', [], true)
 6 APPPATH\Controllers\Home.php(15): view('login_boot')
 7 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->signin()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
CRITICAL - 2023-12-04 05:08:12 --> Undefined variable $username
in APPPATH\Views\connection.php on line 6.
 1 APPPATH\Views\connection.php(6): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $username', 'C:\\xampp\\htdocs\\ci4\\app\\Views\\connection.php', 6)
 2 APPPATH\Views\login_boot.php(2): include('C:\\xampp\\htdocs\\ci4\\app\\Views\\connection.php')
 3 SYSTEMPATH\View\View.php(228): include('C:\\xampp\\htdocs\\ci4\\app\\Views\\login_boot.php')
 4 SYSTEMPATH\View\View.php(231): CodeIgniter\View\View->CodeIgniter\View\{closure}()
 5 SYSTEMPATH\Common.php(1190): CodeIgniter\View\View->render('login_boot', [], true)
 6 APPPATH\Controllers\Home.php(15): view('login_boot')
 7 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\Home->signin()
 8 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-12-04 06:25:33 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), 'ci-4', 3306, '', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ci4\system\Model.php(264): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci4\system\BaseModel.php(662): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\ci4\app\Controllers\LoginController.php(25): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(942): App\Controllers\LoginController->login()
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#9 C:\xampp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\ci4\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\ci4\system\Model.php(264): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\ci4\system\BaseModel.php(662): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\ci4\app\Controllers\LoginController.php(25): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(942): App\Controllers\LoginController->login()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-12-04 06:25:33 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `login`
WHERE `username` IS NULL
AND `password` = :password:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(264): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(662): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\LoginController.php(25): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\LoginController->login()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-12-04 06:25:49 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), 'ci-4', 3306, '', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ci4\system\Model.php(264): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci4\system\BaseModel.php(662): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\ci4\app\Controllers\LoginController.php(25): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(942): App\Controllers\LoginController->login()
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#9 C:\xampp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\ci4\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\ci4\system\Model.php(264): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\ci4\system\BaseModel.php(662): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\ci4\app\Controllers\LoginController.php(25): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(942): App\Controllers\LoginController->login()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-12-04 06:25:49 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `login`
WHERE `username` IS NULL
AND `password` = :password:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(264): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(662): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\LoginController.php(25): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\LoginController->login()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-12-04 06:26:11 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), 'ci-4', 3306, '', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\ci4\system\Model.php(264): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\ci4\system\BaseModel.php(662): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\ci4\app\Controllers\LoginController.php(25): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(942): App\Controllers\LoginController->login()
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#9 C:\xampp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\ci4\index.php(79): CodeIgniter\CodeIgniter->run()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\ci4\system\Model.php(264): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\ci4\system\BaseModel.php(662): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\ci4\app\Controllers\LoginController.php(25): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(942): App\Controllers\LoginController->login()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
CRITICAL - 2023-12-04 06:26:11 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1615): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `login`
WHERE `username` IS NULL
AND `password` = :password:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(264): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(662): CodeIgniter\Model->doFirst()
 5 APPPATH\Controllers\LoginController.php(25): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\LoginController->login()
 7 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 8 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-12-04 06:31:50 --> mysqli_sql_exception: Unknown column 'user_name' in 'where clause' in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT COUNT(*)...', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*)...')
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1699): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\ci4\system\Model.php(599): CodeIgniter\Database\BaseBuilder->countAllResults(true)
#5 C:\xampp\htdocs\ci4\app\Controllers\LoginController.php(40): CodeIgniter\Model->countAllResults()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(942): App\Controllers\LoginController->login()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2023-12-04 06:31:51 --> mysqli_sql_exception: Unknown column 'user_name' in 'where clause' in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT COUNT(*)...', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*)...')
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1699): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\ci4\system\Model.php(599): CodeIgniter\Database\BaseBuilder->countAllResults(true)
#5 C:\xampp\htdocs\ci4\app\Controllers\LoginController.php(40): CodeIgniter\Model->countAllResults()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(942): App\Controllers\LoginController->login()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2023-12-04 06:31:51 --> mysqli_sql_exception: Unknown column 'user_name' in 'where clause' in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT COUNT(*)...', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*)...')
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1699): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\ci4\system\Model.php(599): CodeIgniter\Database\BaseBuilder->countAllResults(true)
#5 C:\xampp\htdocs\ci4\app\Controllers\LoginController.php(40): CodeIgniter\Model->countAllResults()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(942): App\Controllers\LoginController->login()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2023-12-04 06:31:51 --> mysqli_sql_exception: Unknown column 'user_name' in 'where clause' in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT COUNT(*)...', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*)...')
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1699): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\ci4\system\Model.php(599): CodeIgniter\Database\BaseBuilder->countAllResults(true)
#5 C:\xampp\htdocs\ci4\app\Controllers\LoginController.php(40): CodeIgniter\Model->countAllResults()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(942): App\Controllers\LoginController->login()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2023-12-04 06:31:56 --> mysqli_sql_exception: Unknown column 'user_name' in 'where clause' in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT COUNT(*)...', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*)...')
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1699): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\ci4\system\Model.php(599): CodeIgniter\Database\BaseBuilder->countAllResults(true)
#5 C:\xampp\htdocs\ci4\app\Controllers\LoginController.php(40): CodeIgniter\Model->countAllResults()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(942): App\Controllers\LoginController->login()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2023-12-04 06:32:12 --> mysqli_sql_exception: Unknown column 'user_name' in 'where clause' in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT COUNT(*)...', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*)...')
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1699): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\ci4\system\Model.php(599): CodeIgniter\Database\BaseBuilder->countAllResults(true)
#5 C:\xampp\htdocs\ci4\app\Controllers\LoginController.php(40): CodeIgniter\Model->countAllResults()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(942): App\Controllers\LoginController->login()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2023-12-04 06:32:12 --> mysqli_sql_exception: Unknown column 'user_name' in 'where clause' in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT COUNT(*)...', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*)...')
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1699): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\ci4\system\Model.php(599): CodeIgniter\Database\BaseBuilder->countAllResults(true)
#5 C:\xampp\htdocs\ci4\app\Controllers\LoginController.php(40): CodeIgniter\Model->countAllResults()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(942): App\Controllers\LoginController->login()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2023-12-04 06:32:20 --> mysqli_sql_exception: Unknown column 'user_name' in 'where clause' in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT COUNT(*)...', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*)...')
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1699): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\ci4\system\Model.php(599): CodeIgniter\Database\BaseBuilder->countAllResults(true)
#5 C:\xampp\htdocs\ci4\app\Controllers\LoginController.php(40): CodeIgniter\Model->countAllResults()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(942): App\Controllers\LoginController->login()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2023-12-04 06:33:25 --> mysqli_sql_exception: Unknown column 'user_name' in 'where clause' in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT COUNT(*)...', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*)...')
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1699): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\ci4\system\Model.php(599): CodeIgniter\Database\BaseBuilder->countAllResults(true)
#5 C:\xampp\htdocs\ci4\app\Controllers\LoginController.php(40): CodeIgniter\Model->countAllResults()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(942): App\Controllers\LoginController->login()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2023-12-04 06:33:25 --> mysqli_sql_exception: Unknown column 'user_name' in 'where clause' in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT COUNT(*)...', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*)...')
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1699): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\ci4\system\Model.php(599): CodeIgniter\Database\BaseBuilder->countAllResults(true)
#5 C:\xampp\htdocs\ci4\app\Controllers\LoginController.php(40): CodeIgniter\Model->countAllResults()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(942): App\Controllers\LoginController->login()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2023-12-04 06:33:25 --> mysqli_sql_exception: Unknown column 'user_name' in 'where clause' in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT COUNT(*)...', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*)...')
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1699): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\ci4\system\Model.php(599): CodeIgniter\Database\BaseBuilder->countAllResults(true)
#5 C:\xampp\htdocs\ci4\app\Controllers\LoginController.php(40): CodeIgniter\Model->countAllResults()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(942): App\Controllers\LoginController->login()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2023-12-04 06:33:25 --> mysqli_sql_exception: Unknown column 'user_name' in 'where clause' in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT COUNT(*)...', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*)...')
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1699): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\ci4\system\Model.php(599): CodeIgniter\Database\BaseBuilder->countAllResults(true)
#5 C:\xampp\htdocs\ci4\app\Controllers\LoginController.php(40): CodeIgniter\Model->countAllResults()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(942): App\Controllers\LoginController->login()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2023-12-04 06:33:27 --> mysqli_sql_exception: Unknown column 'user_name' in 'where clause' in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT COUNT(*)...', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*)...')
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1699): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\ci4\system\Model.php(599): CodeIgniter\Database\BaseBuilder->countAllResults(true)
#5 C:\xampp\htdocs\ci4\app\Controllers\LoginController.php(40): CodeIgniter\Model->countAllResults()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(942): App\Controllers\LoginController->login()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2023-12-04 06:33:28 --> mysqli_sql_exception: Unknown column 'user_name' in 'where clause' in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT COUNT(*)...', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*)...')
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1699): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\ci4\system\Model.php(599): CodeIgniter\Database\BaseBuilder->countAllResults(true)
#5 C:\xampp\htdocs\ci4\app\Controllers\LoginController.php(40): CodeIgniter\Model->countAllResults()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(942): App\Controllers\LoginController->login()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2023-12-04 06:35:51 --> mysqli_sql_exception: Unknown column 'user_name' in 'where clause' in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT COUNT(*)...', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*)...')
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1699): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\ci4\system\Model.php(599): CodeIgniter\Database\BaseBuilder->countAllResults(true)
#5 C:\xampp\htdocs\ci4\app\Controllers\LoginController.php(40): CodeIgniter\Model->countAllResults()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(942): App\Controllers\LoginController->login()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2023-12-04 06:35:52 --> mysqli_sql_exception: Unknown column 'user_name' in 'where clause' in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT COUNT(*)...', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*)...')
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1699): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\ci4\system\Model.php(599): CodeIgniter\Database\BaseBuilder->countAllResults(true)
#5 C:\xampp\htdocs\ci4\app\Controllers\LoginController.php(40): CodeIgniter\Model->countAllResults()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(942): App\Controllers\LoginController->login()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2023-12-04 06:35:55 --> mysqli_sql_exception: Unknown column 'user_name' in 'where clause' in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT COUNT(*)...', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*)...')
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1699): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\ci4\system\Model.php(599): CodeIgniter\Database\BaseBuilder->countAllResults(true)
#5 C:\xampp\htdocs\ci4\app\Controllers\LoginController.php(40): CodeIgniter\Model->countAllResults()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(942): App\Controllers\LoginController->login()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2023-12-04 06:36:01 --> mysqli_sql_exception: Unknown column 'user_name' in 'where clause' in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT COUNT(*)...', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*)...')
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1699): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\ci4\system\Model.php(599): CodeIgniter\Database\BaseBuilder->countAllResults(true)
#5 C:\xampp\htdocs\ci4\app\Controllers\LoginController.php(40): CodeIgniter\Model->countAllResults()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(942): App\Controllers\LoginController->login()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2023-12-04 06:37:13 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:184
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(184): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), 'ci-4', 3306, '', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1699): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\ci4\system\Model.php(599): CodeIgniter\Database\BaseBuilder->countAllResults(true)
#5 C:\xampp\htdocs\ci4\app\Controllers\LoginController.php(40): CodeIgniter\Model->countAllResults()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(942): App\Controllers\LoginController->login()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:229
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(392): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1699): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#3 C:\xampp\htdocs\ci4\system\Model.php(599): CodeIgniter\Database\BaseBuilder->countAllResults(true)
#4 C:\xampp\htdocs\ci4\app\Controllers\LoginController.php(40): CodeIgniter\Model->countAllResults()
#5 C:\xampp\htdocs\ci4\system\CodeIgniter.php(942): App\Controllers\LoginController->login()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\ci4\index.php(79): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2023-12-04 06:37:13 --> Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
in SYSTEMPATH\Database\BaseConnection.php on line 428.
 1 SYSTEMPATH\Database\BaseConnection.php(575): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1699): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*) AS `numrows`
FROM `login`
WHERE `user_name` = :user_name:
AND `password` = :password:', [...], false)
 3 SYSTEMPATH\Model.php(599): CodeIgniter\Database\BaseBuilder->countAllResults(true)
 4 APPPATH\Controllers\LoginController.php(40): CodeIgniter\Model->countAllResults()
 5 SYSTEMPATH\CodeIgniter.php(942): App\Controllers\LoginController->login()
 6 SYSTEMPATH\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
 7 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
ERROR - 2023-12-04 06:39:53 --> mysqli_sql_exception: Unknown column 'user_name' in 'where clause' in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT COUNT(*)...', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*)...')
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1699): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\ci4\system\Model.php(599): CodeIgniter\Database\BaseBuilder->countAllResults(true)
#5 C:\xampp\htdocs\ci4\app\Controllers\LoginController.php(40): CodeIgniter\Model->countAllResults()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(942): App\Controllers\LoginController->login()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2023-12-04 06:39:59 --> mysqli_sql_exception: Unknown column 'user_name' in 'where clause' in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT COUNT(*)...', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*)...')
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1699): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\ci4\system\Model.php(599): CodeIgniter\Database\BaseBuilder->countAllResults(true)
#5 C:\xampp\htdocs\ci4\app\Controllers\LoginController.php(40): CodeIgniter\Model->countAllResults()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(942): App\Controllers\LoginController->login()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2023-12-04 06:40:08 --> mysqli_sql_exception: Unknown column 'user_name' in 'where clause' in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT COUNT(*)...', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*)...')
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1699): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\ci4\system\Model.php(599): CodeIgniter\Database\BaseBuilder->countAllResults(true)
#5 C:\xampp\htdocs\ci4\app\Controllers\LoginController.php(40): CodeIgniter\Model->countAllResults()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(942): App\Controllers\LoginController->login()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2023-12-04 06:42:02 --> mysqli_sql_exception: Unknown column 'user_name' in 'where clause' in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT COUNT(*)...', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*)...')
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1699): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\ci4\system\Model.php(599): CodeIgniter\Database\BaseBuilder->countAllResults(true)
#5 C:\xampp\htdocs\ci4\app\Controllers\LoginController.php(40): CodeIgniter\Model->countAllResults()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(942): App\Controllers\LoginController->login()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2023-12-04 06:42:04 --> mysqli_sql_exception: Unknown column 'user_name' in 'where clause' in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT COUNT(*)...', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*)...')
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1699): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\ci4\system\Model.php(599): CodeIgniter\Database\BaseBuilder->countAllResults(true)
#5 C:\xampp\htdocs\ci4\app\Controllers\LoginController.php(40): CodeIgniter\Model->countAllResults()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(942): App\Controllers\LoginController->login()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2023-12-04 06:42:05 --> mysqli_sql_exception: Unknown column 'user_name' in 'where clause' in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT COUNT(*)...', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*)...')
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1699): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\ci4\system\Model.php(599): CodeIgniter\Database\BaseBuilder->countAllResults(true)
#5 C:\xampp\htdocs\ci4\app\Controllers\LoginController.php(40): CodeIgniter\Model->countAllResults()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(942): App\Controllers\LoginController->login()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
ERROR - 2023-12-04 06:42:06 --> mysqli_sql_exception: Unknown column 'user_name' in 'where clause' in C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(306): mysqli->query('SELECT COUNT(*)...', 0)
#1 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*)...')
#2 C:\xampp\htdocs\ci4\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#3 C:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1699): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\ci4\system\Model.php(599): CodeIgniter\Database\BaseBuilder->countAllResults(true)
#5 C:\xampp\htdocs\ci4\app\Controllers\LoginController.php(40): CodeIgniter\Model->countAllResults()
#6 C:\xampp\htdocs\ci4\system\CodeIgniter.php(942): App\Controllers\LoginController->login()
#7 C:\xampp\htdocs\ci4\system\CodeIgniter.php(502): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\LoginController))
#8 C:\xampp\htdocs\ci4\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\ci4\index.php(79): CodeIgniter\CodeIgniter->run()
#10 {main}
